import { useState, useEffect } from 'react'
import { runAIQuery, getAIStatus } from '../api/client'
import QueryResultsTable from '../components/QueryResultsTable'

const EXAMPLES = [
  'Show top 20 users by number of events',
  'Which categories have the highest purchase conversion rate?',
  'Show the 10 most recent purchases with product titles',
  'How many users viewed products in the last 7 days?',
]

export default function SQLAssistant() {
  const [question, setQuestion] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [llmStatus, setLlmStatus] = useState(null)

  useEffect(() => {
    getAIStatus()
      .then(({ data }) => setLlmStatus(data))
      .catch(() => setLlmStatus({ llmEnabled: false }))
  }, [])

  const run = async (q) => {
    const query = q || question
    if (!query.trim()) return
    setLoading(true)
    setResult(null)
    try {
      const { data } = await runAIQuery(query)
      setResult({
        generatedSql: data.generatedSql,
        rows: data.data ?? [],
        rowCount: data.rowCount ?? (data.data?.length ?? 0),
        summary: data.summary,
        source: data.source,
      })
    } catch (err) {
      setResult({
        generatedSql: '',
        rows: [{ error: err.response?.data?.error || err.message }],
        rowCount: 0,
        source: 'error',
      })
    } finally {
      setLoading(false)
    }
  }

  const resultRows = result?.rows ?? []

  return (
    <div>
      <h1 className="text-2xl font-bold mb-2">Ask PEP</h1>
      <p className="text-netflix-muted text-sm mb-2">
        Ask in natural language — OpenAI generates PostgreSQL, then we run it on your Retailrocket data.
      </p>
      {llmStatus && (
        <p className="text-xs mb-6">
          {llmStatus.llmEnabled ? (
            <span className="text-green-400">
              ● LLM active ({llmStatus.model || 'gpt-4o-mini'}) — SQL is generated by OpenAI
            </span>
          ) : (
            <span className="text-yellow-400">
              ○ Mock mode — set OPENAI_API_KEY in .env and PEP_USE_MOCK_AI=false, then restart ai-insights
            </span>
          )}
        </p>
      )}

      <div className="bg-netflix-card rounded-xl p-4 border border-white/5 mb-4">
        <textarea
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) run()
          }}
          placeholder="e.g. Show top 20 users by event count in the last week"
          className="w-full bg-black/40 border border-white/10 rounded-lg p-3 text-sm min-h-[80px] resize-y focus:outline-none focus:ring-1 focus:ring-netflix-accent"
        />
        <div className="flex flex-wrap gap-2 mt-3">
          <button
            onClick={() => run()}
            disabled={loading}
            className="px-4 py-2 bg-netflix-accent rounded font-medium text-sm hover:bg-red-600 disabled:opacity-50"
          >
            {loading ? 'Asking OpenAI…' : 'Run Query'}
          </button>
          {EXAMPLES.map((ex) => (
            <button
              key={ex}
              type="button"
              onClick={() => {
                setQuestion(ex)
                run(ex)
              }}
              className="px-3 py-1.5 text-xs rounded bg-white/5 hover:bg-white/10 text-netflix-muted text-left max-w-full"
            >
              {ex}
            </button>
          ))}
        </div>
        <p className="text-[10px] text-netflix-muted mt-2">Tip: Cmd+Enter to run</p>
      </div>

      {result?.summary && (
        <p className="text-sm text-netflix-muted mb-4 italic">{result.summary}</p>
      )}

      {result?.generatedSql && (
        <div className="mb-4">
          <div className="flex items-center gap-2 mb-2">
            <h3 className="text-sm font-semibold text-netflix-muted">Generated SQL</h3>
            {result.source === 'openai' && (
              <span className="text-[10px] px-2 py-0.5 rounded bg-green-500/20 text-green-400">OpenAI</span>
            )}
            {result.source === 'mock' && (
              <span className="text-[10px] px-2 py-0.5 rounded bg-yellow-500/20 text-yellow-400">Mock</span>
            )}
          </div>
          <pre className="bg-black/50 rounded-lg p-4 text-sm overflow-x-auto text-green-400 border border-white/5">
            {result.generatedSql}
          </pre>
        </div>
      )}

      {result && !loading && (
        <QueryResultsTable rows={resultRows} title={`Results (${result.rowCount} rows)`} />
      )}
    </div>
  )
}
