apiVersion: v1
kind: Service
metadata:
  name: dataset-replay
  namespace: pep-prod
  labels:
    app: dataset-replay
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: dataset-replay
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
