apiVersion: v1
kind: Service
metadata:
  name: ai-insights
  namespace: pep-prod
  labels:
    app: ai-insights
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: ai-insights
  ports:
    - name: http
      port: 8085
      targetPort: http
      protocol: TCP
