apiVersion: v1
kind: ConfigMap
metadata:
  name: retention-analytics-config
  namespace: pep-prod
  labels:
    app: retention-analytics
    environment: prod
data:
  PEP_PORT: "8084"
  PEP_KAFKA_BROKERS: "pep-kafka.pep-prod.svc.cluster.local:9092"
  PEP_REDIS_ADDR: "pep-redis.pep-prod.svc.cluster.local:6379"
