apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: pep-prod
  labels:
    app: recommendation
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: recommendation
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
