apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-config
  namespace: pep-sit
  labels:
    app: recommendation
    environment: sit
data:
  PEP_PORT: "8082"
  PEP_KAFKA_BROKERS: "pep-kafka.pep-sit.svc.cluster.local:9092"
