apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: pep-sit
  labels:
    app: frontend
    environment: sit
data:
  default.conf: |
    resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/replay/ {
            set $backend dataset-replay.pep-sit.svc.cluster.local:8081;
            proxy_pass http://$backend$request_uri;
        }
        location /api/recommendations/ {
            set $backend recommendation.pep-sit.svc.cluster.local:8082;
            proxy_pass http://$backend$request_uri;
        }
        location /api/users/ {
            set $backend recommendation.pep-sit.svc.cluster.local:8082;
            proxy_pass http://$backend$request_uri;
        }
        location /api/dashboard/ {
            set $backend engagement.pep-sit.svc.cluster.local:8083;
            proxy_pass http://$backend$request_uri;
        }
        location /api/activity {
            set $backend engagement.pep-sit.svc.cluster.local:8083;
            proxy_pass http://$backend$request_uri;
        }
        location /api/analytics {
            set $backend retention-analytics.pep-sit.svc.cluster.local:8084;
            proxy_pass http://$backend$request_uri;
        }
        location /api/ai/ {
            set $backend ai-insights.pep-sit.svc.cluster.local:8085;
            proxy_pass http://$backend$request_uri;
        }
        location /ws/ {
            set $backend engagement.pep-sit.svc.cluster.local:8083;
            proxy_pass http://$backend$request_uri;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
